import Login from '@/components/Login'
import Navbar from '@/components/Navbar'
import Head from 'next/head'
import Acerca from './Acerca'
import Contact from './Contact'
import Hero from './Hero'
// 
import { useSession, getSession } from 'next-auth/react';



export default function Home() {

// ___ if not session, return Login page
  const {data: session} = useSession();
  if (!session) return <Login />;
 


      return (
        <>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main>
            <Navbar />
            <Hero />
            <Acerca />
            <Contact />
          </main>
        </>
  )
}

// session setup
export async function getServerSideProps(context) {
  const session = await getSession(context);

  return {
    props: {
      session,
    },
  };
}
